<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HMECL002868" ignored="0" name="Default test" tests="7" failures="1" timestamp="25 Feb 2020 09:55:03 GMT" time="11.532" errors="0">
  <testcase name="printallHearders" time="2.181" classname="RestAssuredAPI.RestAssuredAPI.TC004_GET_Request"/>
  <testcase name="ValidateJsonResponse" time="2.092" classname="RestAssuredAPI.RestAssuredAPI.TC005_GET_Request"/>
  <testcase name="ExternalResponse" time="2.028" classname="RestAssuredAPI.RestAssuredAPI.TC006_GET_Request">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;34.3 Degree celsius&amp;gt; but was:&amp;lt;28.56 Degree celsius&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<34.3 Degree celsius> but was:<28.56 Degree celsius>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at RestAssuredAPI.RestAssuredAPI.TC006_GET_Request.ExternalResponse(TC006_GET_Request.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- ExternalResponse -->
  <testcase name="getwheatherdetails" time="1.576" classname="RestAssuredAPI.RestAssuredAPI.TC001_GET_Request"/>
  <testcase name="Googlemaps" time="0.659" classname="RestAssuredAPI.RestAssuredAPI.TC003_GET_Request"/>
  <testcase name="Authentication" time="1.554" classname="RestAssuredAPI.RestAssuredAPI.TC007_GET_Request"/>
  <testcase name="RegistrationCustomer" time="1.4" classname="RestAssuredAPI.RestAssuredAPI.TC002_POST_Request"/>
</testsuite> <!-- Default test -->
